import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const DocumentStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FFF0F5',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 20,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#FFD6E8',
    },
    backButton: {
        padding: 8,
        marginRight: 16,
        borderRadius: 8,
        backgroundColor: '#FFE4EF',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#3D1A26',
    },
    listContent: {
        padding: 20,
        paddingBottom: 40,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#F43F8A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
        flexDirection: 'row',
        alignItems: 'flex-start',
        borderWidth: 1,
        borderColor: '#FFE4EF',
    },
    iconContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#FFD6E8',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    cardContent: {
        flex: 1,
    },
    documentName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3D1A26',
        marginBottom: 4,
    },
    documentMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    documentType: {
        fontSize: 12,
        color: '#C48BA0',
        fontWeight: '500',
        marginRight: 12,
    },
    documentDate: {
        fontSize: 12,
        color: '#DEB8C8',
    },
    documentDescription: {
        fontSize: 14,
        color: '#A07080',
        lineHeight: 20,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyText: {
        fontSize: 16,
        color: '#C48BA0',
        textAlign: 'center',
        marginTop: 16,
    },
    fab: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F43F8A',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#F43F8A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 10,
        elevation: 6,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(61,26,38,0.4)',
        justifyContent: 'flex-end',
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        padding: 24,
        paddingBottom: 40,
        borderTopWidth: 3,
        borderTopColor: '#FFD6E8',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#3D1A26',
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#C48BA0',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#FFF0F5',
        borderWidth: 1,
        borderColor: '#FFD6E8',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        color: '#3D1A26',
        marginBottom: 16,
    },
    textArea: {
        height: 100,
        textAlignVertical: 'top',
    },
    submitButton: {
        backgroundColor: '#F43F8A',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 20,
        shadowColor: '#F43F8A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 8,
        elevation: 4,
    },
    submitButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    deleteButton: {
        padding: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    pickFileButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFE4EF',
        borderWidth: 1,
        borderColor: '#FFB3D0',
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
        gap: 10,
    },
    pickFileText: {
        fontSize: 14,
        color: '#F43F8A',
        fontWeight: '500',
        flex: 1,
    },
    tapToView: {
        fontSize: 12,
        color: '#F43F8A',
        marginTop: 4,
        fontWeight: '500',
    },
    cardActions: {
        flexDirection: 'column',
        alignItems: 'center',
        gap: 10,
        marginLeft: 8,
    },
    viewButton: {
        padding: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
